version: '3'

services:
 pg: 
    image: postgres:15.2-bullseye
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$W*axA#7ukIVuNq+
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    